# Generated by Django 6.0 on 2025-12-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='Category_Image/default_category.jpg', upload_to='Category_Image'),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='cover_image',
            field=models.ImageField(default='Book Cover/default_cover.jpg', upload_to='Book Cover'),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
