# Generated by Django 6.0 on 2025-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_cat_image_alter_addbook_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='isbn',
            field=models.TextField(),
        ),
    ]
