# Generated by Django 6.0 on 2025-12-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('EEE', 'Electrical and Electronics Engineering'), ('ENG', 'English'), ('ARCH', 'Architecture'), ('CSE', 'Computer Science and Engineering'), ('LAW', 'Law'), ('BBA', 'Bachelor of Business Administration')], null=True),
        ),
    ]
