# Generated by Django 6.0 on 2025-12-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ARCH', 'Architecture'), ('BBA', 'Bachelor of Business Administration'), ('ENG', 'English'), ('CSE', 'Computer Science and Engineering'), ('LAW', 'Law'), ('EEE', 'Electrical and Electronics Engineering')], default=None, null=True),
        ),
    ]
