# Generated by Django 6.0 on 2025-12-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ARCH', 'Architecture'), ('ENG', 'English'), ('BBA', 'Bachelor of Business Administration'), ('LAW', 'Law')], default=None, null=True),
        ),
    ]
