# Generated by Django 6.0 on 2025-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ARCH', 'Architecture'), ('CSE', 'Computer Science and Engineering'), ('LAW', 'Law'), ('ENG', 'English'), ('BBA', 'Bachelor of Business Administration'), ('EEE', 'Electrical and Electronics Engineering')], default=None, null=True),
        ),
    ]
