# Generated by Django 6.0 on 2025-12-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ARCH', 'Architecture'), ('BBA', 'Bachelor of Business Administration'), ('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ENG', 'English'), ('LAW', 'Law')], default=None, null=True),
        ),
    ]
