# Generated by Django 6.0 on 2025-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('ARCH', 'Architecture'), ('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('LAW', 'Law'), ('BBA', 'Bachelor of Business Administration')], default=None, null=True),
        ),
    ]
