# Generated by Django 6.0 on 2025-12-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('BBA', 'Bachelor of Business Administration'), ('LAW', 'Law'), ('ENG', 'English'), ('CSE', 'Computer Science and Engineering'), ('ARCH', 'Architecture'), ('EEE', 'Electrical and Electronics Engineering')], default=None, null=True),
        ),
    ]
